# Rewrite from build pandoc from source in alpine (https://github.com/pandoc/dockerfiles/blob/master/alpine/Dockerfile)
FROM alpine:latest AS builder-env

RUN apk --no-cache add alpine-sdk curl ca-certificates fakeroot git linux-headers \
         lua5.4-dev yaml python3-dev py3-virtualenv cabal R R-dev

FROM builder-env AS pandoc-builder
ARG PANDOC_VERSION="3.7.0.2"
COPY cabal.root.config /root/.cabal/config
# clone pandoc
RUN git clone --branch=${PANDOC_VERSION}  --depth=1 --quiet https://github.com/jgm/pandoc /usr/src/pandoc
RUN cabal v2-update -v3
WORKDIR /usr/src/pandoc
## Add lua config
COPY cabal.project.* /usr/src/pandoc
## Build with pandoc-crossref
RUN cabal v2-build --disable-tests --disable-bench --jobs . pandoc-cli pandoc-crossref
RUN find dist-newstyle -name 'pandoc*' -type f -perm -u+x -exec strip '{}' ';' -exec cp '{}' /usr/local/bin/ ';'

FROM builder-env AS python-builder
# Install python filter
RUN python -m venv /venv
ENV PATH=/venv/bin:$PATH
RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \
    pip3 install -r /tmp/requirements.txt

FROM builder-env AS R-builder
COPY ./R_CMD_INSTALL_patch /usr/lib/R/bin/INSTALL
RUN Rscript -e "install.packages(c('knitr', 'rmarkdown'), repos='https://cran.rstudio.com')"

FROM gcr.io/distroless/cc AS gnu-lib

FROM alpine:latest
# Load repo
COPY repositories /etc/apk/repositories
# prepare texlive font
COPY 09-texlive-fonts.conf /etc/fonts/conf.d/99-texlive-fonts.conf
# Install python filter
COPY --from=python-builder /venv /venv
## use instructor from https://github.com/denoland/deno_docker/blob/main/alpine.dockerfile
COPY --from=gnu-lib --chown=root:root --chmod=755 /lib/*-linux-gnu/* /lib64/
RUN ln -s /lib64/ld-linux-* /lib
# Install pandoc
COPY --from=pandoc-builder /usr/local/bin/pandoc* /usr/local/bin
# Copy R lib
COPY --from=R-builder /usr/lib/R/library /usr/lib/R/library
COPY ./R_CMD_INSTALL_patch /usr/lib/R/bin/INSTALL
# Load env
ENV XDG_DATA_HOME=/usr/local/share
ENV PATH="/venv/bin:${PATH}"
ENV LD_LIBRARY_PATH=/lib:/usr/lib:/lib64
ENTRYPOINT ["/usr/local/bin/pandoc"]