FROM surnet/alpine-wkhtmltopdf:3.20.0-0.12.6-full AS wkhtmltopdf

FROM alpine:latest AS quarto-installer
RUN apk add tar
ARG QUARTO_VER="1.5.57"
ARG TARGETARCH
ADD https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VER}/quarto-${QUARTO_VER}-linux-${TARGETARCH}.tar.gz /quarto.tar.gz
RUN tar -xvzf quarto.tar.gz \
    && mv quarto-${QUARTO_VER} /quarto

FROM ngocptblaplafla/pandoc-texlive-full:temp-do-not-use
# Install app & font -> install js filter -> delete unused
RUN --mount=type=bind,source=requirements.txt,target=/requirements.txt \
    apk --no-cache add lua5.4-lpeg librsvg perl python3 npm texlive-full asymptote wget zip git typst groff \
    plantuml graphviz chromium-swiftshader font-noto-cjk-extra tar font-jetbrains-mono msttcorefonts-installer tectonic \
    && update-ms-fonts && fc-cache -r -v && pip3 install -r /requirements.txt \
    && npm install -g @mermaid-js/mermaid-cli pagedjs-cli --omit=dev --loglevel verbose \
    && rm -rf /repositories /usr/share/man/* /usr/share/doc/* /usr/share/info/* /root/.cache /root/.npm \
    /usr/share/texmf-dist/source /usr/share/texmf-dist/fonts/source /tmp/* \
    && echo 'LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib64" /quarto/bin/quarto $@' > /usr/local/bin/quarto && chmod +x /usr/local/bin/quarto
# Add wkhtmltopdf
COPY --from=wkhtmltopdf /bin/wkhtmlto* /usr/local/bin
# Copy quarto
COPY --from=quarto-installer /quarto /quarto
# Copy pandoc, filter and template
COPY --chmod=755 ./pandoc /usr/local/share/pandoc
# Add execute to path
ENV PATH="$(npm root -g)/.bin:${PATH}"
WORKDIR /workspace
# Add env for filter
ENV MERMAID_CONF=/usr/local/share/pandoc/puppeteer-config.json
ENV HOME=/tmp/tritiumd
ENV XDG_CONFIG_HOME=$HOME/.config
ENV XDG_CACHE_HOME=$HOME/.cache
# Add default user
RUN adduser --disabled-password tritiumd && chmod 777 /workspace
USER tritiumd
ENTRYPOINT ["/usr/local/bin/pandoc"]


