name: nightly-release

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  nightly-release:
    if: "github.event.release.prerelease"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export LATEST_TAG
        run: |
          echo "TAG=$(curl -qsSL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
          echo ${{env.TAG}}
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install template and delete some unused data
        run: sh clean.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ngocptblaplafla/pandoc-texlive-full:nightly
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ngocptblaplafla/pandoc-texlive-full:nightly
            ngocptblaplafla/pandoc-texlive-full:${{ steps.date.outputs.time }}
            ngocptblaplafla/pandoc-texlive-full:${{env.TAG}}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ngocptblaplafla/pandoc-texlive-full
