name: nightly-patch

on: [workflow_dispatch]
jobs:
  nightly-patch:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install components
        run: sh install-components.sh
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: pandoc-assets
          path: pandoc-assets.zip
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Update build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.update
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ngocptblaplafla/pandoc-texlive-full:nightly
            ngocptblaplafla/pandoc-texlive-full:${{ steps.date.outputs.time }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ngocptblaplafla/pandoc-texlive-full
