name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install template and delete some unused data
        run: sh clean.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: pandoc-texlive-full:latest
      - name: Build and push latest stable release
        if: "!github.event.release.prerelease"
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ngocptblaplafla/pandoc-texlive-full:latest
            ngocptblaplafla/pandoc-texlive-full:${{github.ref_name}}
      - name: Build and push latest nightly release
        if: "github.event.release.prerelease"
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ngocptblaplafla/pandoc-texlive-full:nightly
            ngocptblaplafla/pandoc-texlive-full:${{ steps.date.outputs.time }}
            ngocptblaplafla/pandoc-texlive-full:${{github.ref_name}}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ngocptblaplafla/pandoc-texlive-full
